spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AQBetJZ5Ff/ldGwS4KxKQw92mKok8KEUMrn+tvMOWd7U8qAd4ZiMUqzGeBQ7SXIZsERoJ1afwjLOvdmN8Y14Vkn6ddRaKJwvFJUsZz8yfTOrPvdu0GUN3Bf/0FTNKD8QE0bDvu3aezzD7N7i/EEcYphtugUcohA6PX7mzbKnJCgLv/YzUyf29jEUNaIJUTnc9NpWcT7PS9nK2hicX6z+LclzDBOkAdXOO5AACX2NTMEjYzHiFYkQcO7TnMQOTfj3U62svOvcSlstDjQ2TtXRaV7TR6BXr48JCyofukFaq9gV3eTBezKzMtoAziWpOKktRLERg4qp4a//YlaEDsky/dNu4IwAw9esRtyF96m2wbWUpTM87WbyIEbXqOhjtliywQQ='

app:
  payment:
    apiToken: '{cipher}AYBiqIwR47EUXVMiUUgQA3MY65xE1hPU53UhatBAH5eoDPTnWnUBggXrGYtBCgy2+wpCZieRQLYA1w+pA6U81RdD/FyEVKwxEoPfuwgQaaFNPBkbxKc1Ag1ot1jpGM+P5uiROQ5bSd40Dh6Yzf+crbZwpe4szLddmJ7fs4NaHCT4OEsRrEpe2wPZwnGyTQQyH05N4O7WVhNFnSqS8IWHnmRjkKTgMW8gFYt1f1pZ8uUaFo71vjQ9zrcwjtIGJuXepq2001XW3/y+oKkXLmoHlbWlUxS9auuRI7QpZIqBjrIqjQ74pdHsyVwIyl6I690UleggooE8WmSs/EFQipsLOLJG8ShLisuKnZcG4xn+cw2OTt8YNCZpH2HojSCVP5RmsFnrvoli3IbdLNme8dD95yg7jQZvGZLyZGtA4HNdqerXCtDSleFcxvzCu3LW1AOv0lhfxMT70qBXlMjX2bHtnmCJ/ZABESX6nXoUB3GFSmWHvmEr0pixEQMOmIb77p6i0t6NOSgz2Qt7RjxnhgMlbUBsp9l83cHeDt4E1BDkHp8VccghjEfAI0jVoSPULOQdOVs='

logging:
  level:
    root: INFO

greeting:
  message: user-service-remote-default-last-update
